# TCL File Generated by Component Editor 17.1
# Sun May 13 23:31:11 CEST 2018
# DO NOT MODIFY


# 
# clk_gen "clk_gen" v1.0
#  2018.05.13.23:31:11
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module clk_gen
# 
set_module_property DESCRIPTION ""
set_module_property NAME clk_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME clk_gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL clk_gen_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file clk_gen_wrapper.vhd VHDL PATH ../platform_designer_wrappers/clk_gen_wrapper.vhd TOP_LEVEL_FILE
add_fileset_file clk_gen.vhd VHDL PATH ../../logical/clk_gen.vhd
add_fileset_file sc_ff.vhd VHDL PATH ../../logical/sc_ff.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_rstn reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point trig_out
# 
add_interface trig_out conduit end
set_interface_property trig_out associatedClock clock
set_interface_property trig_out associatedReset ""
set_interface_property trig_out ENABLED true
set_interface_property trig_out EXPORT_OF ""
set_interface_property trig_out PORT_NAME_MAP ""
set_interface_property trig_out CMSIS_SVD_VARIABLES ""
set_interface_property trig_out SVD_ADDRESS_GROUP ""

add_interface_port trig_out trig_out new_signal Output 1


# 
# connection point clk_out
# 
add_interface clk_out clock start
set_interface_property clk_out associatedDirectClock ""
set_interface_property clk_out clockRate 0
set_interface_property clk_out clockRateKnown false
set_interface_property clk_out ENABLED true
set_interface_property clk_out EXPORT_OF ""
set_interface_property clk_out PORT_NAME_MAP ""
set_interface_property clk_out CMSIS_SVD_VARIABLES ""
set_interface_property clk_out SVD_ADDRESS_GROUP ""

add_interface_port clk_out clk_out clk Output 1


# 
# connection point AVS
# 
add_interface AVS avalon end
set_interface_property AVS addressUnits WORDS
set_interface_property AVS associatedClock clock
set_interface_property AVS associatedReset reset
set_interface_property AVS bitsPerSymbol 8
set_interface_property AVS burstOnBurstBoundariesOnly false
set_interface_property AVS burstcountUnits WORDS
set_interface_property AVS explicitAddressSpan 0
set_interface_property AVS holdTime 0
set_interface_property AVS linewrapBursts false
set_interface_property AVS maximumPendingReadTransactions 0
set_interface_property AVS maximumPendingWriteTransactions 0
set_interface_property AVS readLatency 0
set_interface_property AVS readWaitStates 0
set_interface_property AVS readWaitTime 0
set_interface_property AVS setupTime 0
set_interface_property AVS timingUnits Cycles
set_interface_property AVS writeWaitTime 0
set_interface_property AVS ENABLED true
set_interface_property AVS EXPORT_OF ""
set_interface_property AVS PORT_NAME_MAP ""
set_interface_property AVS CMSIS_SVD_VARIABLES ""
set_interface_property AVS SVD_ADDRESS_GROUP ""

add_interface_port AVS avs_write write Input 1
add_interface_port AVS avs_writedata writedata Input 32
add_interface_port AVS avs_readdata readdata Output 32
set_interface_assignment AVS embeddedsw.configuration.isFlash 0
set_interface_assignment AVS embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS embeddedsw.configuration.isPrintableDevice 0

