# TCL File Generated by Component Editor 17.1
# Sun May 13 23:30:42 CEST 2018
# DO NOT MODIFY


# 
# dct_2d_ip "dct_2d_ip" v1.0
#  2018.05.13.23:30:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dct_2d_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME dct_2d_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dct_2d_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dct_2d_ip_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dct_2d_ip_wrapper.vhd VHDL PATH ../../ip/dct_2d/implementation/platform_designer_wrapper/dct_2d_ip_wrapper.vhd TOP_LEVEL_FILE
add_fileset_file DCT_2D.vhd VHDL PATH ../../ip/dct_2d/logical/DCT_2D.vhd
add_fileset_file DCT_2D_wrapper.vhd VHDL PATH ../../ip/dct_2d/logical/DCT_2D_wrapper.vhd
add_fileset_file dct_package.vhd VHDL PATH ../../ip/dct_2d/logical/dct_package.vhd
add_fileset_file loeff_1D_DCT.vhd VHDL PATH ../../ip/dct_2d/logical/loeff_1D_DCT.vhd
add_fileset_file loeff_A1.vhd VHDL PATH ../../ip/dct_2d/logical/loeff_A1.vhd
add_fileset_file loeff_A2.vhd VHDL PATH ../../ip/dct_2d/logical/loeff_A2.vhd
add_fileset_file loeff_A3.vhd VHDL PATH ../../ip/dct_2d/logical/loeff_A3.vhd
add_fileset_file loeff_A4.vhd VHDL PATH ../../ip/dct_2d/logical/loeff_A4.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_rstn reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dct_done
# 
add_interface dct_done conduit end
set_interface_property dct_done associatedClock clock
set_interface_property dct_done associatedReset reset
set_interface_property dct_done ENABLED true
set_interface_property dct_done EXPORT_OF ""
set_interface_property dct_done PORT_NAME_MAP ""
set_interface_property dct_done CMSIS_SVD_VARIABLES ""
set_interface_property dct_done SVD_ADDRESS_GROUP ""

add_interface_port dct_done dct_done new_signal Output 1


# 
# connection point busy
# 
add_interface busy conduit end
set_interface_property busy associatedClock clock
set_interface_property busy associatedReset reset
set_interface_property busy ENABLED true
set_interface_property busy EXPORT_OF ""
set_interface_property busy PORT_NAME_MAP ""
set_interface_property busy CMSIS_SVD_VARIABLES ""
set_interface_property busy SVD_ADDRESS_GROUP ""

add_interface_port busy busy new_signal Output 1


# 
# connection point start_dct
# 
add_interface start_dct conduit end
set_interface_property start_dct associatedClock clock
set_interface_property start_dct associatedReset reset
set_interface_property start_dct ENABLED true
set_interface_property start_dct EXPORT_OF ""
set_interface_property start_dct PORT_NAME_MAP ""
set_interface_property start_dct CMSIS_SVD_VARIABLES ""
set_interface_property start_dct SVD_ADDRESS_GROUP ""

add_interface_port start_dct start_dct new_signal Input 1


# 
# connection point new_output
# 
add_interface new_output conduit end
set_interface_property new_output associatedClock clock
set_interface_property new_output associatedReset reset
set_interface_property new_output ENABLED true
set_interface_property new_output EXPORT_OF ""
set_interface_property new_output PORT_NAME_MAP ""
set_interface_property new_output CMSIS_SVD_VARIABLES ""
set_interface_property new_output SVD_ADDRESS_GROUP ""

add_interface_port new_output new_output new_signal Output 1


# 
# connection point new_output_data
# 
add_interface new_output_data conduit end
set_interface_property new_output_data associatedClock clock
set_interface_property new_output_data associatedReset reset
set_interface_property new_output_data ENABLED true
set_interface_property new_output_data EXPORT_OF ""
set_interface_property new_output_data PORT_NAME_MAP ""
set_interface_property new_output_data CMSIS_SVD_VARIABLES ""
set_interface_property new_output_data SVD_ADDRESS_GROUP ""

add_interface_port new_output_data new_output_data new_signal Output 32

