# TCL File Generated by Component Editor 17.1
# Sun May 13 23:30:14 CEST 2018
# DO NOT MODIFY


# 
# delta_timer "delta_timer" v1.0
#  2018.05.13.23:30:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module delta_timer
# 
set_module_property DESCRIPTION ""
set_module_property NAME delta_timer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME delta_timer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL delta_timer_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file delta_timer_wrapper.vhd VHDL PATH ../platform_designer_wrappers/delta_timer_wrapper.vhd TOP_LEVEL_FILE
add_fileset_file chg_det.vhd VHDL PATH ../../logical/chg_det.vhd
add_fileset_file chg_det_fsm.vhd VHDL PATH ../../logical/chg_det_fsm.vhd
add_fileset_file cntr.vhd VHDL PATH ../../logical/cntr.vhd
add_fileset_file delta_timer.vhd VHDL PATH ../../logical/delta_timer.vhd
add_fileset_file delta_timer_fsm.vhd VHDL PATH ../../logical/delta_timer_fsm.vhd
add_fileset_file sc_ff.vhd VHDL PATH ../../logical/sc_ff.vhd


# 
# parameters
# 
add_parameter REG_LAYER BOOLEAN false
set_parameter_property REG_LAYER DEFAULT_VALUE false
set_parameter_property REG_LAYER DISPLAY_NAME REG_LAYER
set_parameter_property REG_LAYER TYPE BOOLEAN
set_parameter_property REG_LAYER UNITS None
set_parameter_property REG_LAYER HDL_PARAMETER true
add_parameter CW INTEGER 7
set_parameter_property CW DEFAULT_VALUE 7
set_parameter_property CW DISPLAY_NAME CW
set_parameter_property CW TYPE INTEGER
set_parameter_property CW UNITS None
set_parameter_property CW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_rstn reset_n Input 1


# 
# connection point AVS
# 
add_interface AVS avalon end
set_interface_property AVS addressUnits WORDS
set_interface_property AVS associatedClock clock
set_interface_property AVS associatedReset reset
set_interface_property AVS bitsPerSymbol 8
set_interface_property AVS burstOnBurstBoundariesOnly false
set_interface_property AVS burstcountUnits WORDS
set_interface_property AVS explicitAddressSpan 0
set_interface_property AVS holdTime 0
set_interface_property AVS linewrapBursts false
set_interface_property AVS maximumPendingReadTransactions 0
set_interface_property AVS maximumPendingWriteTransactions 0
set_interface_property AVS readLatency 0
set_interface_property AVS readWaitStates 0
set_interface_property AVS readWaitTime 0
set_interface_property AVS setupTime 0
set_interface_property AVS timingUnits Cycles
set_interface_property AVS writeWaitTime 0
set_interface_property AVS ENABLED true
set_interface_property AVS EXPORT_OF ""
set_interface_property AVS PORT_NAME_MAP ""
set_interface_property AVS CMSIS_SVD_VARIABLES ""
set_interface_property AVS SVD_ADDRESS_GROUP ""

add_interface_port AVS avs_write write Input 1
add_interface_port AVS avs_writedata writedata Input 32
add_interface_port AVS avs_readdata readdata Output 32
set_interface_assignment AVS embeddedsw.configuration.isFlash 0
set_interface_assignment AVS embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVS embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVS embeddedsw.configuration.isPrintableDevice 0


# 
# connection point trig_in
# 
add_interface trig_in conduit end
set_interface_property trig_in associatedClock clock
set_interface_property trig_in associatedReset reset
set_interface_property trig_in ENABLED true
set_interface_property trig_in EXPORT_OF ""
set_interface_property trig_in PORT_NAME_MAP ""
set_interface_property trig_in CMSIS_SVD_VARIABLES ""
set_interface_property trig_in SVD_ADDRESS_GROUP ""

add_interface_port trig_in trig_in new_signal Input 1


# 
# connection point signal_from_DUV
# 
add_interface signal_from_DUV conduit end
set_interface_property signal_from_DUV associatedClock clock
set_interface_property signal_from_DUV associatedReset reset
set_interface_property signal_from_DUV ENABLED true
set_interface_property signal_from_DUV EXPORT_OF ""
set_interface_property signal_from_DUV PORT_NAME_MAP ""
set_interface_property signal_from_DUV CMSIS_SVD_VARIABLES ""
set_interface_property signal_from_DUV SVD_ADDRESS_GROUP ""

add_interface_port signal_from_DUV signal_from_DUV new_signal Input 1


# 
# connection point trig_out
# 
add_interface trig_out conduit end
set_interface_property trig_out associatedClock clock
set_interface_property trig_out associatedReset reset
set_interface_property trig_out ENABLED true
set_interface_property trig_out EXPORT_OF ""
set_interface_property trig_out PORT_NAME_MAP ""
set_interface_property trig_out CMSIS_SVD_VARIABLES ""
set_interface_property trig_out SVD_ADDRESS_GROUP ""

add_interface_port trig_out trig_out new_signal Output 1

